# Generated by Django 4.2.7 on 2025-05-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_from', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_to', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('flight_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('flight_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotelName', models.CharField(blank=True, max_length=255, null=True)),
                ('hotelPlace', models.CharField(blank=True, max_length=255, null=True)),
                ('checkin_date', models.DateField(blank=True, null=True)),
                ('checkout_date', models.DateField(blank=True, null=True)),
                ('hotelStar', models.CharField(blank=True, choices=[('5', '5 Star'), ('4', '4 Star'), ('3', '3 Star'), ('ECONOMY', 'Economy')], max_length=10, null=True)),
                ('room_type', models.CharField(blank=True, choices=[('PENTA', 'Penta'), ('QUAD', 'Quad'), ('TRIPLE', 'Triple'), ('DOUBLE', 'Double'), ('SHARING', 'Sharing')], max_length=10, null=True)),
                ('hotel_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hotel_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packageName', models.CharField(max_length=255)),
                ('packageType', models.CharField(choices=[('LOCAL', 'Local'), ('INTERNATIONAL', 'International')], max_length=20)),
                ('place', models.JSONField(blank=True, null=True)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('is_hotel', models.BooleanField(default=False)),
                ('is_flight', models.BooleanField(default=False)),
                ('is_transfers', models.BooleanField(default=False)),
                ('package_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('package_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='travel_packages/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Travel Package',
                'verbose_name_plural': 'Travel Packages',
            },
        ),
        migrations.CreateModel(
            name='TravelTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(blank=True, choices=[('BUS', 'Bus'), ('COASTER', 'Coaster'), ('HIACE', 'Hiace'), ('SEDAN', 'Sedan')], max_length=10, null=True)),
                ('transferPlace', models.CharField(blank=True, max_length=255, null=True)),
                ('transfer_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transfer_selling_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
