# Generated by Django 4.2.7 on 2025-05-29 19:48

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationRouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(db_index=True, max_length=255)),
                ('locations', models.JSONField(default=dict)),
                ('assigned_users', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'location_routing',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_id'], name='location_ro_tenant__5d5adc_idx'), django.contrib.postgres.indexes.GinIndex(fields=['locations'], name='location_ro_locatio_b6d490_gin'), django.contrib.postgres.indexes.GinIndex(fields=['assigned_users'], name='location_ro_assigne_3786c3_gin')],
            },
        ),
    ]
