# Generated by Django 4.2.7 on 2025-03-27 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('lead_id', models.UUIDField(blank=True, help_text='UUID of associated lead', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_chats', to='users.tenant')),
            ],
            options={
                'ordering': ['-last_message_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('sent_by_contact', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField()),
                ('is_image', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='waba_int.chat')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='users.tenant')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['message_id'], name='waba_int_me_message_7b1f5d_idx'), models.Index(fields=['-timestamp'], name='waba_int_me_timesta_2d4ebb_idx')],
                'unique_together': {('message_id', 'tenant')},
            },
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['contact_id'], name='waba_int_ch_contact_06d283_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['phone'], name='waba_int_ch_phone_2b9ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['lead_id'], name='waba_int_ch_lead_id_4aa4df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('contact_id', 'tenant')},
        ),
    ]
