# Generated by Django 4.2.7 on 2025-05-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WABASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='https://apps.oncloudapi.com')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=255, null=True)),
                ('business_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waba_settings', to='users.tenant')),
            ],
            options={
                'verbose_name': 'WABA Settings',
                'verbose_name_plural': 'WABA Settings',
                'db_table': 'waba_settings',
            },
        ),
        migrations.CreateModel(
            name='ChatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_chats', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_assignments', to='users.tenant')),
            ],
            options={
                'db_table': 'chat_assignments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('lead_id', models.UUIDField(blank=True, help_text='UUID of associated lead', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='waba_int.chatassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_chats', to='users.tenant')),
            ],
            options={
                'ordering': ['-last_message_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255)),
                ('text', models.TextField(blank=True, null=True)),
                ('sent_by_contact', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField()),
                ('is_image', models.BooleanField(default=False)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='waba_int.chat')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_messages', to='users.tenant')),
            ],
            options={
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['message_id'], name='waba_int_me_message_7b1f5d_idx'), models.Index(fields=['-timestamp'], name='waba_int_me_timesta_2d4ebb_idx')],
                'unique_together': {('message_id', 'tenant')},
            },
        ),
        migrations.AddIndex(
            model_name='chatassignment',
            index=models.Index(fields=['chat_id'], name='chat_assign_chat_id_49b2ed_idx'),
        ),
        migrations.AddIndex(
            model_name='chatassignment',
            index=models.Index(fields=['tenant'], name='chat_assign_tenant__918987_idx'),
        ),
        migrations.AddIndex(
            model_name='chatassignment',
            index=models.Index(fields=['assigned_to'], name='chat_assign_assigne_9c22d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chatassignment',
            unique_together={('chat_id', 'tenant')},
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['contact_id'], name='waba_int_ch_contact_06d283_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['phone'], name='waba_int_ch_phone_2b9ca6_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['lead_id'], name='waba_int_ch_lead_id_4aa4df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chat',
            unique_together={('contact_id', 'tenant')},
        ),
    ]
