# Generated by Django 5.1.6 on 2025-04-08 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department'),
        ('waba_int', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WABASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField(default='https://apps.oncloudapi.com')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=255, null=True)),
                ('business_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255, null=True)),
                ('webhook_url', models.URLField(blank=True, null=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waba_settings', to='users.tenant')),
            ],
            options={
                'verbose_name': 'WABA Settings',
                'verbose_name_plural': 'WABA Settings',
                'db_table': 'waba_settings',
            },
        ),
    ]
