# Generated by Django 5.1.6 on 2025-04-13 18:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CannedMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_name', models.CharField(help_text='Name of the message template', max_length=100)),
                ('template_message', models.TextField(help_text='Message template with support for emoji and formatting')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canned_messages', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_messages', to='users.tenant')),
            ],
            options={
                'verbose_name': 'Canned Message',
                'verbose_name_plural': 'Canned Messages',
                'ordering': ['template_name'],
                'indexes': [models.Index(fields=['tenant'], name='canned_mess_tenant__428ef7_idx'), models.Index(fields=['is_active'], name='canned_mess_is_acti_8ad95f_idx')],
                'unique_together': {('template_name', 'tenant')},
            },
        ),
    ]
