# Generated by Django 4.2.7 on 2025-05-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canned_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cannedmessage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_canned_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cannedmessage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canned_messages', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='cannedmessage',
            index=models.Index(fields=['tenant'], name='canned_mess_tenant__428ef7_idx'),
        ),
        migrations.AddIndex(
            model_name='cannedmessage',
            index=models.Index(fields=['is_active'], name='canned_mess_is_acti_8ad95f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cannedmessage',
            unique_together={('template_name', 'tenant')},
        ),
    ]
