# Generated by Django 5.1.6 on 2025-04-06 18:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_user_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('visa', models.CharField(choices=[('included', 'Included'), ('not_included', 'Not Included')], default='included', max_length=20)),
                ('transportation', models.CharField(choices=[('included', 'Included'), ('not_included', 'Not Included')], default='included', max_length=20)),
                ('vehicle_type', models.CharField(blank=True, choices=[('coaster', 'Coaster'), ('bus', 'Bus'), ('SUV', 'SUV'), ('sedan', 'Sedan'), ('van', 'Van'), ('ministry_approved_bus', 'Ministry Approved Bus')], max_length=30, null=True)),
                ('flight_carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('ziyarat', models.CharField(choices=[('makkah_madinah', 'Makkah & Madinah'), ('makkah_only', 'Makkah Only'), ('madinah_only', 'Madinah Only'), ('not_included', 'Not Included')], default='makkah_madinah', max_length=20)),
                ('package_star', models.CharField(choices=[('5', '5 Star'), ('4', '4 Star'), ('3', '3 Star'), ('2', '2 Star'), ('economy', 'Economy'), ('sharing', 'Sharing')], max_length=20)),
                ('umrah_days', models.PositiveIntegerField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='umrah_packages/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_umrah_packages', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umrah_packages', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UmrahHotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_city', models.CharField(choices=[('Makkah', 'Makkah'), ('Madinah', 'Madinah')], max_length=10)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('hotel_star', models.CharField(choices=[('5', '5 Star'), ('4', '4 Star'), ('3', '3 Star'), ('2', '2 Star'), ('economy', 'Economy'), ('sharing', 'Sharing')], max_length=20)),
                ('hotel_room_type', models.CharField(choices=[('Double', 'Double'), ('Triple', 'Triple'), ('Quad', 'Quad'), ('Penta', 'Penta'), ('Hexa', 'Hexa'), ('Economy', 'Economy'), ('Sharing', 'Sharing')], max_length=20)),
                ('no_of_nights', models.PositiveIntegerField(default=0)),
                ('buying_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('umrah_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='umrahPackages.umrahpackage')),
            ],
            options={
                'ordering': ['hotel_city', 'checkin_date'],
            },
        ),
        migrations.AddIndex(
            model_name='umrahpackage',
            index=models.Index(fields=['package_name'], name='umrahPackag_package_c0ce88_idx'),
        ),
        migrations.AddIndex(
            model_name='umrahpackage',
            index=models.Index(fields=['departure_date'], name='umrahPackag_departu_658b92_idx'),
        ),
        migrations.AddIndex(
            model_name='umrahpackage',
            index=models.Index(fields=['is_active'], name='umrahPackag_is_acti_96e339_idx'),
        ),
    ]
