# Generated by Django 4.2.7 on 2025-05-29 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahHotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=255)),
                ('hotel_city', models.CharField(choices=[('Makkah', 'Makkah'), ('Madinah', 'Madinah')], max_length=10)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('hotel_star', models.CharField(choices=[('5', '5 Star'), ('4', '4 Star'), ('3', '3 Star'), ('2', '2 Star'), ('economy', 'Economy'), ('sharing', 'Sharing')], max_length=20)),
                ('hotel_room_type', models.CharField(choices=[('Double', 'Double'), ('Triple', 'Triple'), ('Quad', 'Quad'), ('Penta', 'Penta'), ('Hexa', 'Hexa'), ('Economy', 'Economy'), ('Sharing', 'Sharing')], max_length=20)),
                ('no_of_nights', models.PositiveIntegerField(default=0)),
                ('buying_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hotel_city', 'checkin_date'],
            },
        ),
        migrations.CreateModel(
            name='UmrahPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('visa', models.CharField(choices=[('included', 'Included'), ('not_included', 'Not Included')], default='included', max_length=20)),
                ('transportation', models.CharField(choices=[('included', 'Included'), ('not_included', 'Not Included')], default='included', max_length=20)),
                ('vehicle_type', models.CharField(blank=True, choices=[('coaster', 'Coaster'), ('bus', 'Bus'), ('SUV', 'SUV'), ('sedan', 'Sedan'), ('van', 'Van'), ('ministry_approved_bus', 'Ministry Approved Bus')], max_length=30, null=True)),
                ('flight_carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('ziyarat', models.CharField(choices=[('makkah_madinah', 'Makkah & Madinah'), ('makkah_only', 'Makkah Only'), ('madinah_only', 'Madinah Only'), ('not_included', 'Not Included')], default='makkah_madinah', max_length=20)),
                ('package_star', models.CharField(choices=[('5', '5 Star'), ('4', '4 Star'), ('3', '3 Star'), ('2', '2 Star'), ('economy', 'Economy'), ('sharing', 'Sharing')], max_length=20)),
                ('umrah_days', models.PositiveIntegerField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='umrah_packages/')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
