# Generated by Django 4.2.7 on 2025-05-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('umrahPackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umrahpackage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_umrah_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='umrahpackage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umrah_packages', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='umrahhotel',
            name='umrah_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='umrahPackages.umrahpackage'),
        ),
        migrations.AddIndex(
            model_name='umrahpackage',
            index=models.Index(fields=['package_name'], name='umrahPackag_package_c0ce88_idx'),
        ),
        migrations.AddIndex(
            model_name='umrahpackage',
            index=models.Index(fields=['departure_date'], name='umrahPackag_departu_658b92_idx'),
        ),
        migrations.AddIndex(
            model_name='umrahpackage',
            index=models.Index(fields=['is_active'], name='umrahPackag_is_acti_96e339_idx'),
        ),
    ]
