# Generated by Django 5.1.6 on 2025-03-20 01:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HajjPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('visa', models.CharField(choices=[('included', 'Included'), ('not_included', 'Not Included')], default='included', max_length=20)),
                ('ziyarat', models.CharField(choices=[('makkah_medinah', 'Makkah & Medinah'), ('not_included', 'Not Included')], default='makkah_medinah', max_length=20)),
                ('flight_carrier', models.CharField(max_length=255)),
                ('package_star', models.CharField(choices=[('5', '5 Star'), ('4', '4 Star'), ('3', '3 Star'), ('2', '2 Star'), ('economy', 'Economy'), ('sharing', 'Sharing')], max_length=20)),
                ('hajj_days', models.PositiveIntegerField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('maktab_no', models.CharField(blank=True, max_length=50, null=True)),
                ('hotel_makkah', models.CharField(max_length=255)),
                ('makkah_star', models.CharField(choices=[('5', '5 Star'), ('4', '4 Star'), ('3', '3 Star'), ('2', '2 Star'), ('economy', 'Economy'), ('sharing', 'Sharing')], max_length=20)),
                ('makkah_check_in', models.DateField(blank=True, null=True)),
                ('makkah_check_out', models.DateField(blank=True, null=True)),
                ('makkah_room_type', models.CharField(choices=[('Double', 'Double'), ('Triple', 'Triple'), ('Quad', 'Quad'), ('Penta', 'Penta'), ('Hexa', 'Hexa'), ('Sharing', 'Sharing'), ('Economy', 'Economy')], max_length=20)),
                ('makkah_nights', models.PositiveIntegerField(default=0)),
                ('hotel_madinah', models.CharField(max_length=255)),
                ('madinah_star', models.CharField(choices=[('5', '5 Star'), ('4', '4 Star'), ('3', '3 Star'), ('2', '2 Star'), ('economy', 'Economy'), ('sharing', 'Sharing')], max_length=20)),
                ('madinah_check_in', models.DateField(blank=True, null=True)),
                ('madinah_check_out', models.DateField(blank=True, null=True)),
                ('madinah_room_type', models.CharField(choices=[('Double', 'Double'), ('Triple', 'Triple'), ('Quad', 'Quad'), ('Penta', 'Penta'), ('Hexa', 'Hexa'), ('Sharing', 'Sharing'), ('Economy', 'Economy')], max_length=20)),
                ('madinah_nights', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hajj_packages/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hajj_packages', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hajj_packages', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hajj_packages', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['package_name'], name='hajjPackage_package_13a253_idx'), models.Index(fields=['departure_date'], name='hajjPackage_departu_91c554_idx'), models.Index(fields=['is_active'], name='hajjPackage_is_acti_43d128_idx')],
            },
        ),
    ]
