# Generated by Django 5.1.6 on 2025-03-08 08:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_tenantuser_industry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HajjPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_name', models.CharField(max_length=255)),
                ('hujjaj', models.JSONField(help_text='JSON object storing number of adults, children, infants')),
                ('hajj_days', models.PositiveIntegerField()),
                ('hajj_star', models.PositiveIntegerField(help_text='Star rating of the Hajj package')),
                ('hajj_start_date', models.DateField()),
                ('hajj_end_date', models.DateField()),
                ('hotel_makkah', models.CharField(max_length=255)),
                ('hotel_medina', models.CharField(max_length=255)),
                ('maktab_no', models.CharField(blank=True, max_length=50, null=True)),
                ('room_type', models.CharField(choices=[('Double', 'Double'), ('Triple', 'Triple'), ('Quad', 'Quad'), ('Penta', 'Penta'), ('Hexa', 'Hexa'), ('Sharing', 'Sharing')], max_length=20)),
                ('flight', models.CharField(max_length=255)),
                ('flight_carrier', models.CharField(max_length=255)),
                ('visa', models.CharField(max_length=255)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hajj_packages', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hajj_packages', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hajj_packages', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant'], name='hajjPackage_tenant__ab6199_idx'), models.Index(fields=['assigned_to'], name='hajjPackage_assigne_68bd12_idx'), models.Index(fields=['hajj_start_date'], name='hajjPackage_hajj_st_23851b_idx'), models.Index(fields=['is_active'], name='hajjPackage_is_acti_43d128_idx')],
            },
        ),
    ]
