# Generated by Django 4.2.7 on 2025-05-29 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hajjPackages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hajjpackage',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hajj_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hajjpackage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hajj_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hajjpackage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hajj_packages', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='hajjpackage',
            index=models.Index(fields=['package_name'], name='hajjPackage_package_13a253_idx'),
        ),
        migrations.AddIndex(
            model_name='hajjpackage',
            index=models.Index(fields=['departure_date'], name='hajjPackage_departu_91c554_idx'),
        ),
        migrations.AddIndex(
            model_name='hajjpackage',
            index=models.Index(fields=['is_active'], name='hajjPackage_is_acti_43d128_idx'),
        ),
    ]
