# Generated by Django 4.2.7 on 2025-04-23 21:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_tenantuser_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_products', to='users.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
