# Generated by Django 4.2.7 on 2025-05-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('generalProduct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalproduct',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_products', to='users.tenant'),
        ),
    ]
