# Generated by Django 5.1.6 on 2025-04-03 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
        ('leads', '0003_lead_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='leads.lead'),
        ),
    ]
