# Generated by Django 4.2.7 on 2025-04-18 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department'),
        ('invoices', '0002_invoice_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_histories', to='users.tenant'),
        ),
    ]
