# Generated by Django 4.2.7 on 2025-03-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='chat_id',
            field=models.CharField(blank=True, help_text='WhatsApp chat ID if lead originated from WhatsApp', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['chat_id'], name='leads_lead_chat_id_f2a949_idx'),
        ),
    ]
