# Generated by Django 5.1.6 on 2025-03-15 21:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaddocument',
            name='document_type',
        ),
        migrations.AddField(
            model_name='leaddocument',
            name='document_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Name or description of the document', max_length=255),
            preserve_default=False,
        ),
    ]
