# Generated by Django 5.1.6 on 2025-03-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_remove_leaddocument_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadactivity',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='leadactivity',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='leadactivity',
            name='duration',
        ),
        migrations.AlterField(
            model_name='leadactivity',
            name='activity_type',
            field=models.CharField(max_length=100),
        ),
    ]
