# Generated by Django 5.1.6 on 2025-04-05 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hajjPackages', '0001_initial'),
        ('leads', '0003_lead_department'),
        ('users', '0002_user_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_leads', to='users.branch'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['branch'], name='leads_lead_branch__9ddaaa_idx'),
        ),
    ]
