# Generated by Django 5.1.6 on 2025-04-07 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_branch_lead_leads_lead_branch__9ddaaa_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='flight',
            field=models.JSONField(blank=True, help_text='Flight details for flight leads', null=True),
        ),
    ]
