# Generated by Django 4.2.7 on 2025-04-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('hajj_package', 'Hajj Package'), ('custom_umrah', 'Custom Umrah'), ('readymade_umrah', 'Readymade Umrah'), ('flight', 'Flight'), ('visa', 'Visa'), ('transfer', 'Transfer'), ('ziyarat', 'Ziyarat'), ('study_visa', 'Study Visa'), ('visit_visa', 'Visit Visa'), ('skilled_immigration', 'Skilled Immigration'), ('job_visa', 'Job Visa'), ('trc', 'TRC'), ('business_immigration', 'Business Immigration'), ('travel_package', 'Travel Package')], default='hajj_package', max_length=50),
        ),
    ]
