# Generated by Django 4.2.7 on 2025-04-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_lead_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='development_project',
            field=models.CharField(blank=True, help_text='Development project ID for real estate leads', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('hajj_package', 'Hajj Package'), ('custom_umrah', 'Custom Umrah'), ('readymade_umrah', 'Readymade Umrah'), ('flight', 'Flight'), ('visa', 'Visa'), ('transfer', 'Transfer'), ('ziyarat', 'Ziyarat'), ('study_visa', 'Study Visa'), ('visit_visa', 'Visit Visa'), ('skilled_immigration', 'Skilled Immigration'), ('job_visa', 'Job Visa'), ('trc', 'TRC'), ('business_immigration', 'Business Immigration'), ('travel_package', 'Travel Package'), ('development_project', 'Development Project')], default='hajj_package', max_length=50),
        ),
    ]
