# Generated by Django 4.2.7 on 2025-04-23 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generalProduct', '0001_initial'),
        ('leads', '0008_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='hajj_package',
        ),
        migrations.AddField(
            model_name='lead',
            name='general_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='generalProduct.generalproduct'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(help_text='Lead type - can be predefined or from general products', max_length=50),
        ),
    ]
