# Generated by Django 4.2.7 on 2025-04-23 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hajjPackages', '0001_initial'),
        ('leads', '0009_remove_lead_hajj_package_lead_general_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='hajj_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='hajjPackages.hajjpackage'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(default='hajj_package', help_text='Lead type - can be predefined or from general products', max_length=50),
        ),
    ]
