# Generated by Django 4.2.7 on 2025-05-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_lead_hajj_package_alter_lead_lead_type'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_lead_status_e23abe_idx',
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'phone'], name='leads_lead_tenant__d4b2e7_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'whatsapp'], name='leads_lead_tenant__50a3d1_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'status'], name='leads_lead_tenant__054659_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['tenant', 'created_at'], name='leads_lead_tenant__5e5f75_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(fields=('tenant', 'phone'), name='unique_tenant_phone'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('whatsapp__isnull', False)), fields=('tenant', 'whatsapp'), name='unique_tenant_whatsapp'),
        ),
    ]
