# Generated by Django 5.1.6 on 2025-04-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysettings',
            name='phone',
            field=models.CharField(max_length=17),
        ),
    ]
