# Generated by Django 5.1.6 on 2025-04-07 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelling_from', models.CharField(max_length=100)),
                ('travelling_to', models.CharField(max_length=100)),
                ('travel_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('passengers', models.JSONField(default=dict)),
                ('pnr', models.CharField(max_length=20, unique=True)),
                ('ticket_status', models.CharField(choices=[('inquiry', 'Inquiry'), ('booking', 'Booking'), ('issued', 'Issued'), ('cancelled', 'Cancelled'), ('refund', 'Refund')], default='inquiry', max_length=20)),
                ('carrier', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_flights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adult_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('child_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('infant_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_sell', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_details', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Cost Detail',
                'verbose_name_plural': 'Cost Details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PassengerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_fname', models.CharField(max_length=100)),
                ('passenger_lname', models.CharField(max_length=100)),
                ('passport_no', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flight_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_details', to='flights.flight')),
            ],
            options={
                'verbose_name': 'Passenger Detail',
                'verbose_name_plural': 'Passenger Details',
                'ordering': ['-created_at'],
            },
        ),
    ]
