# Generated by Django 5.1.6 on 2025-04-07 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
        ('leads', '0005_lead_flight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='lead_inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flight_inquiries', to='leads.lead'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='carrier',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='flight',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_flights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='flight',
            name='pnr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='flight',
            name='travel_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
