# Generated by Django 5.1.6 on 2025-04-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_flight_lead_inquiry_alter_flight_carrier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passengerdetail',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='passengerdetail',
            name='passport_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
