# Generated by Django 5.1.6 on 2025-04-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_qualification', models.CharField(max_length=255)),
                ('last_qualification_yr', models.IntegerField()),
                ('ielts_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('study_program', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('student_assesment', models.TextField()),
                ('can_manage_bs', models.BooleanField(default=False)),
                ('consultation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
