# Generated by Django 5.1.6 on 2025-04-09 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0006_alter_lead_lead_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyInquiry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_qualification', models.CharField(choices=[('phd', 'PhD'), ('phil', 'Phil'), ('msc', 'MSc'), ('ma', 'MA'), ('mcom', 'MCom'), ('mcs', 'MCS'), ('mbbs', 'MBBS'), ('bsc', 'BSc'), ('ba', 'BA'), ('bcs', 'BCS'), ('bsit', 'BSIT'), ('bcom', 'BCom'), ('ca', 'CA'), ('fa', 'FA'), ('fsc', 'FSc'), ('metric', 'Metric'), ('other', 'Other')], max_length=20)),
                ('country', models.CharField(choices=[('usa', 'USA'), ('canada', 'Canada'), ('uk', 'UK'), ('italy', 'Italy'), ('france', 'France'), ('sweden', 'Sweden'), ('china', 'China'), ('turkey', 'Turkey'), ('malaysia', 'Malaysia'), ('australia', 'Australia'), ('new_zealand', 'New Zealand'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead_inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_inquiries', to='leads.lead')),
            ],
            options={
                'verbose_name': 'Study Inquiry',
                'verbose_name_plural': 'Study Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyEligibility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manage_bankstatement', models.BooleanField(default=False)),
                ('required_ielts', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('not_required', 'Not Required')], default='yes', max_length=20)),
                ('educational_requirements', models.CharField(choices=[('completed', 'Completed'), ('not_completed', 'Not Completed'), ('not_required', 'Not Required')], default='not_completed', max_length=20)),
                ('final_assessment', models.CharField(choices=[('eligible', 'Eligible'), ('not_eligible', 'Not Eligible')], default='not_eligible', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='study.studyinquiry')),
            ],
            options={
                'verbose_name': 'Study Eligibility',
                'verbose_name_plural': 'Study Eligibilities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('uni_rebate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('study_inquiry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost', to='study.studyinquiry')),
            ],
            options={
                'verbose_name': 'Study Cost',
                'verbose_name_plural': 'Study Costs',
                'ordering': ['-created_at'],
            },
        ),
    ]
