# Generated by Django 5.1.6 on 2025-04-10 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_study_lead_inquiry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study',
            options={'ordering': ['-created_at'], 'verbose_name': 'Study', 'verbose_name_plural': 'Studies'},
        ),
    ]
