# Generated by Django 5.1.6 on 2025-03-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='industry',
            field=models.CharField(blank=True, choices=[('hajj_umrah', 'Hajj and Umrah'), ('travel_tourism', 'Travel and Tourism'), ('immigration', 'Immigration Consultancy'), ('real_estate', 'Real Estate'), ('ecommerce', 'Ecommerce')], max_length=50, null=True),
        ),
    ]
