# Generated by Django 4.2.7 on 2025-04-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='industry',
            field=models.CharField(blank=True, choices=[('hajj_umrah', 'Hajj and Umrah'), ('travel_tourism', 'Travel and Tourism'), ('immigration', 'Immigration Consultancy'), ('real_estate', 'Real Estate'), ('ecommerce', 'Ecommerce'), ('general', 'General')], max_length=50, null=True),
        ),
    ]
