# Generated by Django 5.1.6 on 2025-03-19 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tenantuser_industry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='tenant',
        ),
    ]
