# Generated by Django 4.2.7 on 2025-05-29 19:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookIntegrationSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, help_text='Whether the Facebook integration is active')),
                ('albato_integration_id', models.CharField(blank=True, help_text='Integration ID from Albato', max_length=255, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret key for webhook verification', max_length=255, null=True)),
                ('default_assigned_to', models.JSONField(blank=True, help_text='List of user IDs for round-robin lead assignment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facebook Integration Settings',
                'verbose_name_plural': 'Facebook Integration Settings',
            },
        ),
        migrations.CreateModel(
            name='FacebookWebhookHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_data', models.JSONField(help_text='Raw data received from the webhook')),
                ('processed', models.BooleanField(default=False, help_text='Whether this webhook data has been processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this webhook data was processed', null=True)),
                ('lead_created', models.BooleanField(default=False, help_text='Whether a lead was created from this webhook')),
                ('lead_id', models.UUIDField(blank=True, help_text='ID of the lead created from this webhook', null=True)),
                ('error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Facebook webhook histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
