# Generated by Django 4.2.7 on 2025-05-29 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('fb_webhook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookwebhookhistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fb_webhook_history', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='facebookintegrationsettings',
            name='tenant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facebook_settings', to='users.tenant'),
        ),
        migrations.AddIndex(
            model_name='facebookwebhookhistory',
            index=models.Index(fields=['-created_at'], name='fb_webhook__created_a72e40_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookwebhookhistory',
            index=models.Index(fields=['processed'], name='fb_webhook__process_e665a1_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookwebhookhistory',
            index=models.Index(fields=['lead_created'], name='fb_webhook__lead_cr_c6ffca_idx'),
        ),
    ]
