# Generated by Django 4.2.7 on 2025-04-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_webhook', '0003_rename_fb_webhook__created__8af84f_idx_fb_webhook__created_a72e40_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookintegrationsettings',
            name='default_assigned_to',
            field=models.JSONField(blank=True, help_text='List of user IDs for round-robin lead assignment', null=True),
        ),
    ]
